name: Auto Update On-chain Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# ---------------------------------------------------------
# KARTU AKSES: Memberikan izin robot untuk menyimpan file CSV
# ---------------------------------------------------------
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Membuka repositori
      uses: actions/checkout@v4 # (Diupdate ke v4 agar warning kuning hilang)

    - name: Menyiapkan Python
      uses: actions/setup-python@v5 # (Diupdate ke v5)
      with:
        python-version: '3.10'

    - name: Menginstal bahan yang dibutuhkan (Pandas & Requests)
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Menjalankan script auto_update.py
      run: python auto_update.py

    - name: Menyimpan hasil CSV kembali ke GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update data dari API" && git push)
